### ISSUE TITLE
Outdated CMI API

### ISSUE THREAD

**Issue by Ksewedo5** [CryptoMorin/KingdomsX#52]
**LibreForge v4.2.0**
`[17:12:08] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to libreforge v4.2.0
java.lang.NoSuchMethodError: 'boolean org.kingdoms.constants.group.Kingdom.hasAttribute(org.kingdoms.constants.group.Kingdom, org.kingdoms.constants.group.model.relationships.StandardRelationAttribute)'
	at com.willfp.eco.internal.spigot.integrations.antigrief.AntigriefKingdoms.canBreakBlock(AntigriefKingdoms.kt:32) ~[eco-6.53.1-all.jar:?]
	at com.willfp.eco.internal.spigot.integrations.antigrief.AntigriefKingdoms.canPlaceBlock(AntigriefKingdoms.kt:51) ~[eco-6.53.1-all.jar:?]
	at com.willfp.eco.core.integrations.antigrief.AntigriefManager.lambda$canPlaceBlock$5(AntigriefManager.java:86) ~[eco-6.53.1-all.jar:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?]
	at com.willfp.eco.core.integrations.antigrief.AntigriefManager.canPlaceBlock(AntigriefManager.java:86) ~[eco-6.53.1-all.jar:?]
	at com.willfp.libreforge.triggers.impl.TriggerPlaceBlock.handle(TriggerPlaceBlock.kt:24) ~[libreforge-4.2.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1373.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-448]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-448]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-448]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:397) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:404) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:590) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1959) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]`

**EcoJobs plugin also doesn't work when Kingdoms is installed on server (Tested)**

The problem also occurs with the CMI plugin (is.God...) now I can't find the error that was appearing, if it occurs again I will paste it here
**CMI**
`[22:30:12 WARN]: [KingdomsX] Task #1210 for Kingdoms v1.16.3.3 generated an exception
java.lang.NoSuchMethodError: 'java.lang.Boolean com.Zrips.CMI.Containers.CMIUser.isGod()'
        at org.kingdoms.services.vanish.ServiceCMI.isInGodMode(ServiceCMI.java:14) ~[KingdomsX-1.16.3.3.jar:?]
        at org.kingdoms.services.managers.ServiceHandler.lambda$isInGodMode$2(ServiceHandler.java:114) ~[KingdomsX-1.16.3.3.jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at org.kingdoms.services.managers.ServiceHandler.isInGodMode(ServiceHandler.java:114) ~[KingdomsX-1.16.3.3.jar:?]
        at org.kingdoms.managers.turrets.TurretTask.run(TurretTask.java:115) ~[KingdomsX-1.16.3.3.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Turrets sometimes work and stop (possibly conflict with CMI)

PufferFish(Paper fork, tested on paperspigot, the same) 1.19.4, Kingdoms(1.16.3.3), CMI(9.5.0.2), EcoJobs (3.2.0)

**Comment by CryptoMorin** [comment]
The first error is because of an outdated API being used. It's not a bug with this plugin.

As for the second error, it looks like CMI updated their API too. I'll update it in the next version. And yes, turrets not working is because of that second error.

**Comment by Theroh** [comment]
The problem with libreforge.
I contacted ECO's support and this is their asnwer:

-Yikes, seems like the kingdoms dev broke the api once again...
-This is an issue on eco's side but the kingdoms dev keeps breaking the api without any notice and there aren't even javadocs for that plugin. Fixing that is going to be pain lmao
-This method **DOES** exist in latest kingdoms
And I've checked it multiple times
But as soon as Kingoms dev sees the "NoSuchMethodError", he just says "They use old API" and doesn't look into it any further

I dont wish to start a fight, I just wish to my plugins to work properly I even donated to kingdom because I liked the concept, so please fix this issue or contact ECO's side

I hope you have a good morning,
Thank you for your attention,
Kindly,
Kube

**Comment by CryptoMorin** [comment]
Update: The Eco issue has been fixed. You should update your eco plugins to fix the error.

And thanks for clarifying that you don't use CMI, I thought you were using it.

**Comment by Ksewedo5** [comment]
@Theroh 
When will the patch be released?

**Comment by CryptoMorin** [comment]
I've taken a look at the CMI bug, you said you don't use CMI, but this issue will not happen unless you use CMI. No one else is experiencing this issue and most of them don't have CMI installed, including me. So please provide reproduction steps.

**Comment by Ksewedo5** [comment]
https://youtu.be/i8vdP2LmpFs <--- You can see what it looks like from my perspective

Sorry, there may have been a mistake. I use google translate. 

Errors related to "Eco" plugins still occur.
`[15:50:56 ERROR]: Could not pass event BlockPlaceEvent to libreforge v4.2.5
java.lang.NoSuchMethodError: 'boolean org.kingdoms.constants.group.Kingdom.hasAttribute(org.kingdoms.constants.group.Kingdom, org.kingdoms.constants.group.model.relationships.StandardRelationAttribute)'
        at com.willfp.eco.internal.spigot.integrations.antigrief.AntigriefKingdoms.canBreakBlock(AntigriefKingdoms.kt:32) ~[eco-6.53.1-all.jar:?]
        at com.willfp.eco.internal.spigot.integrations.antigrief.AntigriefKingdoms.canPlaceBlock(AntigriefKingdoms.kt:51) ~[eco-6.53.1-all.jar:?]
        at com.willfp.eco.core.integrations.antigrief.AntigriefManager.lambda$canPlaceBlock$5(AntigriefManager.java:86) ~[eco-6.53.1-all.jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?]
        at com.willfp.eco.core.integrations.antigrief.AntigriefManager.canPlaceBlock(AntigriefManager.java:86) ~[eco-6.53.1-all.jar:?]
        at com.willfp.libreforge.triggers.impl.TriggerPlaceBlock.handle(TriggerPlaceBlock.kt:24) ~[libreforge-4.2.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1365.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfishplus-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[pufferfishplus-api-1.19.4-R0.1-SNAPSHOT.jar:git-PufferfishPlusPurpur-18]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfishplus-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfishplus-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callBlockPlaceEvent() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.level.ServerPlayerGameMode.a(ServerPlayerGameMode.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.util.thread.BlockableEventLoop.d(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.d(ReentrantBlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.util.thread.BlockableEventLoop.x(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.util.thread.BlockableEventLoop.c(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

And CMI 
`[19:47:16 WARN]: [KingdomsX] Task #1210 for Kingdoms v1.16.3.3 generated an exception
java.lang.NoSuchMethodError: 'java.lang.Boolean com.Zrips.CMI.Containers.CMIUser.isGod()'
        at org.kingdoms.services.vanish.ServiceCMI.isInGodMode(ServiceCMI.java:14) ~[KingdomsX-1.16.3.3.jar:?]
        at org.kingdoms.services.managers.ServiceHandler.lambda$isInGodMode$2(ServiceHandler.java:114) ~[KingdomsX-1.16.3.3.jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at org.kingdoms.services.managers.ServiceHandler.isInGodMode(ServiceHandler.java:114) ~[KingdomsX-1.16.3.3.jar:?]
        at org.kingdoms.managers.turrets.TurretTask.run(TurretTask.java:115) ~[KingdomsX-1.16.3.3.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-18]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`
